services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db


  app-test:
    build:
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env-test
    environment:
      - ENV=TEST
      - PYTHONPATH=/app
    entrypoint: ["sh", "-c",
      "python /app/tests/create_test_database.py
       && pytest -v 
       && uvicorn main:app --reload --host 0.0.0.0 --port 8080"]


  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load database credentials from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
