services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db
#    entrypoint: ["python", "/app/create_test_database.py"]


  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load database credentials from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
